---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: weather-app-backend
  namespace: tenant-staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    platform.fh-burgenland.at/tenant: staging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-app-backend
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 30s
