---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-helm
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-gcp
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
    iam.gke.io/gcp-service-account: crossplane-sa@project-03eb5b2f-b0b9-4171-b14.iam.gserviceaccount.com
