---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers: []
          serviceAccountName: provider-kubernetes
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers: []
          serviceAccountName: provider-helm
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers: []
          serviceAccountName: provider-gcp
